### New section

In [ ]:
pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.3.2-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.13)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.4.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.9.6)
Collecting url-normalize>=2.0 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 3.2 MB/s eta 0:00:00
Downloading requests_cache-1.3.2-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 3.8 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 3.5 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-26.1.0 chembl_webresource_client-0.10.9 requests-cache-1.3.2 url-normalize-3.0.0

In [ ]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

In [ ]:
# Target search for diabetes(type 2)
target_diabetes = new_client.target
target_query = target_diabetes.search('dipeptidyl peptidase 4')
targets = pd.DataFrame.from_dict(target_query)
#displaying results in a tabular format from chembl database
targets

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Sus scrofa,Dipeptidyl peptidase 4,35.0,False,CHEMBL3813,"[{'accession': 'P22411', 'component_descriptio...",SINGLE PROTEIN,9823.0
1,[],Mus musculus,Dipeptidyl peptidase 4,35.0,False,CHEMBL3883,"[{'accession': 'P28843', 'component_descriptio...",SINGLE PROTEIN,10090.0
2,[],Bos taurus,Dipeptidyl peptidase 4,34.0,False,CHEMBL2559,"[{'accession': 'P81425', 'component_descriptio...",SINGLE PROTEIN,9913.0
3,[],Rattus norvegicus,Dipeptidyl peptidase 4,34.0,False,CHEMBL4653,"[{'accession': 'P14740', 'component_descriptio...",SINGLE PROTEIN,10116.0
4,[],Homo sapiens,Dipeptidyl peptidase 4,34.0,False,CHEMBL284,"[{'accession': 'P27487', 'component_descriptio...",SINGLE PROTEIN,9606.0
...,...,...,...,...,...,...,...,...,...
1315,[],Severe acute respiratory syndrome coronavirus 2,Protein cereblon-SARS-Cov-2 polyprotein,1.0,False,CHEMBL6067603,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049.0
1316,[],Severe acute respiratory syndrome coronavirus 2,von Hippel-Lindau disease tumor suppressor-SAR...,1.0,False,CHEMBL6067604,"[{'accession': 'P40337', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,2697049.0
1317,[],Homo sapiens,Sodium channel alpha subunit,0.0,False,CHEMBL2331043,"[{'accession': 'P35498', 'component_descriptio...",PROTEIN FAMILY,9606.0
1318,[],Escherichia coli,1-deoxy-D-xylulose 5-phosphate reductoisomerase,0.0,False,CHEMBL3421521,"[{'accession': 'W8T2T2', 'component_descriptio...",SINGLE PROTEIN,562.0
1319,[],Mus musculus,RNA polymerase II,0.0,False,CHEMBL6066856,"[{'accession': 'P08775', 'component_descriptio...",PROTEIN COMPLEX,10090.0

In [ ]:
final_target = targets.target_chembl_id[4]
final_target

'CHEMBL284'

In [ ]:
activity = new_client.activity
res = activity.filter(target_chembl_id=final_target).filter(standard_type="IC50")
df = pd.DataFrame.from_dict(res)
df

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,105501,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,217.0
1,None,None,106644,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,41.0
2,None,None,106647,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,15.0
3,None,None,106650,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,500.0
4,None,None,108924,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,None,1259011,28946948,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,2070.0
5748,None,1259018,28946969,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,92.0
5749,None,1259024,28946987,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,1.4
5750,None,1259031,28947008,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,1.4
5751,None,1259038,28947029,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,9.3

In [ ]:
df.to_csv('DPP4 raw data chembl 1.csv', index=False)

In [ ]:
#line1-remove data from table where ic50 is absent, line 2-remove rows where chemical structre is missing
df2 = df[df.standard_value.notna()]
df2 = df2[df.canonical_smiles.notna()]
df2

/tmp/ipykernel_2882/3358094881.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df2 = df2[df.canonical_smiles.notna()]

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,105501,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,217.0
1,None,None,106644,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,41.0
2,None,None,106647,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,15.0
3,None,None,106650,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,500.0
4,None,None,108924,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5747,None,1259011,28946948,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,2070.0
5748,None,1259018,28946969,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,92.0
5749,None,1259024,28946987,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,1.4
5750,None,1259031,28947008,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,1.4
5751,None,1259038,28947029,[],CHEMBL5739048,In Vitro Inhibition Assay: Materials: Enzymes ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,9.3

In [ ]:
#count number of molecules, with their uniqueness(no repeatation of compound)
len(df2.canonical_smiles.unique())

4696

In [ ]:
#line1:- a buildin functioin in panda , it scan smiles column to avoid multiple entry of single molecule
df2_nr = df2.drop_duplicates(['canonical_smiles'])
df2_nr

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,105501,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,217.0
1,None,None,106644,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,41.0
2,None,None,106647,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,15.0
3,None,None,106650,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,500.0
4,None,None,108924,[],CHEMBL666573,In vitro inhibition of human Dipeptidylpeptida...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,uM,UO_0000065,None,188.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5687,None,1225560,28854866,[],CHEMBL5738704,DPPIV Enzymatic Activity Assay: DPPIV enzymati...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,1000.0
5703,None,1245034,28908593,[],CHEMBL5738962,EnPlex (purified enzyme activity assay): This ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,7900.0
5717,None,1245118,28908845,[],CHEMBL5738962,EnPlex (purified enzyme activity assay): This ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,20270.0
5718,None,1245124,28908863,[],CHEMBL5738962,EnPlex (purified enzyme activity assay): This ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,9818.0
5725,None,1245168,28908995,[],CHEMBL5738962,EnPlex (purified enzyme activity assay): This ...,B,None,None,BAO_0000190,...,Homo sapiens,Dipeptidyl peptidase 4,9606,None,None,IC50,nM,UO_0000065,None,21000.0

In [ ]:
#this line of code remove unnessecary data from the source
#line1:-Yeh simply ek list bana raha hai un sirf 3 columns ki, jo humare model ke liye actually zaroori hain.
#line2-pichle table (df2_nr) par ek filter lagata hai. Yeh computer ko bolta hai: "Mujhe sirf yeh 3 columns chahiye jo maine selection list mein likhe hain. Baaki ke saare 40+ columns delete kar do aur is naye, chote, aur saaf table ko df3 naam
selection = ['molecule_chembl_id','canonical_smiles','standard_value']
df3 = df2_nr[selection]
df3

,molecule_chembl_id,canonical_smiles,standard_value
0,CHEMBL93558,N[C@@H](CC1CCCCC1)C(=O)N1CCCCC1,217000.0
1,CHEMBL443622,C[C@H](N)C(=O)N1CCCC1,41000.0
2,CHEMBL403882,O=C([C@@H]1CCCN1)N1CCCC1,15000.0
3,CHEMBL328655,S=C(C1CCCN1)N1CCCC1,500000.0
4,CHEMBL328795,NC(=O)CC(N)C(=O)N1CCCC1,188000.0
...,...,...,...
5687,CHEMBL5947027,C[C@H](NC(=O)c1ccncc1-c1ccccc1)C(=O)N1CC(F)(F)...,1000.0
5703,CHEMBL6014809,CC[C@@H](C)C(N)C(=O)N1Cc2ccc(F)cc2C1,7900.0
5717,CHEMBL5874480,CC(C)[C@H](N)C(=O)N1Cc2ccc(F)cc2C1,20270.0
5718,CHEMBL6060914,CC(C)(C)[C@H](N)C(=O)N1Cc2ccc(F)cc2C1,9818.0
5725,CHEMBL5846428,CC(C)[C@@H](C(=O)N1CCC[C@H]1B(O)O)N(C)C,21000.0

In [ ]:
df3.to_csv('DPP4 raw data chembl 1.csv', index=False)

In [ ]:
df4 = pd.read_csv('DPP4 raw data chembl 1.csv')

bioactivity_threshold = []
for i in df4.standard_value:
  if float(i) >= 10000:
    bioactivity_threshold.append("inactive")
  elif float(i) <= 1000:
    bioactivity_threshold.append("active")
  else:
    bioactivity_threshold.append("intermediate")


bioactivity_class = pd.Series(bioactivity_threshold, name='class')
df5 = pd.concat([df4, bioactivity_class], axis=1)
df5

,molecule_chembl_id,canonical_smiles,standard_value,class
0,CHEMBL93558,N[C@@H](CC1CCCCC1)C(=O)N1CCCCC1,217000.0,inactive
1,CHEMBL443622,C[C@H](N)C(=O)N1CCCC1,41000.0,inactive
2,CHEMBL403882,O=C([C@@H]1CCCN1)N1CCCC1,15000.0,inactive
3,CHEMBL328655,S=C(C1CCCN1)N1CCCC1,500000.0,inactive
4,CHEMBL328795,NC(=O)CC(N)C(=O)N1CCCC1,188000.0,inactive
...,...,...,...,...
4691,CHEMBL5947027,C[C@H](NC(=O)c1ccncc1-c1ccccc1)C(=O)N1CC(F)(F)...,1000.0,active
4692,CHEMBL6014809,CC[C@@H](C)C(N)C(=O)N1Cc2ccc(F)cc2C1,7900.0,intermediate
4693,CHEMBL5874480,CC(C)[C@H](N)C(=O)N1Cc2ccc(F)cc2C1,20270.0,inactive
4694,CHEMBL6060914,CC(C)(C)[C@H](N)C(=O)N1Cc2ccc(F)cc2C1,9818.0,intermediate
4695,CHEMBL5846428,CC(C)[C@@H](C(=O)N1CCC[C@H]1B(O)O)N(C)C,21000.0,inactive

In [ ]:
df5.to_csv('DPP4 raw data chembl 1.csv', index=False)
! zip dpp-4.zip *.csv

  adding: DPP4 raw data chembl 1.csv (deflated 84%)

In [ ]:
! ls -l

total 456
-rw-r--r-- 1 root root 394130 May 20 08:18 'DPP4 raw data chembl 1.csv'
-rw-r--r-- 1 root root  63893 May 20 08:18  dpp-4.zip
drwxr-xr-x 1 root root   4096 May 12 13:29  sample_data

In [ ]:
from google.colab import drive
drive.mount('/content/drive')